[package]
name = "easycommerce_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
jsonwebtoken = "8.2.0"
serde = "1.0.152"
chrono = "0.4.23"